### ISSUE TITLE
Documentation for Javadoc

### ISSUE THREAD

**Issue by theNerd247** [theNerd247/JavaCSVReader#16]
If someone would like to manage the javadoc clean up behind the latest stable releases then that would be awesome. Since we are using the git-flow style of work management this should be easy. Pull requests to master on the origin repo will be reviewed. Once all the code is settled and works then we'll make the call to whom ever is handling javadoc and we'll wait on them to make the last commit to the code - which would contain the properly formatted javadoc. Once the javadoc is included then we'll accept  the pull request. 

Any other ideas on how we can manage the javadoc for this?

**Comment by laserswald** [comment]
You should be able to add it to the build file: I'll check it out.

**Comment by theNerd247** [comment]
ok, If not I can manually go in and add in javadoc.

**Comment by laserswald** [comment]
Well, the source files need to be pre-commented in the correct way. The good news is that there are about four correct ways of doing it.

**Comment by laserswald** [comment]
We need some package or other so we don't need to start specifying source files by hand in the build file. If we don't specify a package, it will ask for individual source files, which are hella unscaleable.

@theNerd247: Why not organize it into some package dealio, and then I can edit the build file and push it over to you.

**Comment by theNerd247** [comment]
that's what I'm working on. I'm gonna repush to origin/master that contains corrected comments and package info.
The patches should be up by tomorrow.

**Comment by laserswald** [comment]
Sweet.

**Comment by theNerd247** [comment]
Ok, so I officially hate dealing with packages. I'm getting some odd compiling issues that are dealing with packages. So the wait for the next merge to master is going to have to be extended.

**Comment by theNerd247** [comment]
Ok, so I officially hate dealing with packages. I'm getting some odd compiling issues that are dealing with packages. So the wait for the next merge to master is going to have to be extended.

**Comment by theNerd247** [comment]
Problem solved! Expect merge to master by this evening

**Comment by theNerd247** [comment]
Merge is added to master. 

@laserdude11: What format do the comments need to be in?

**Comment by laserswald** [comment]
https://en.wikipedia.org/wiki/Javadoc

**Comment by theNerd247** [comment]
That works.

**Comment by theNerd247** [comment]
Ok, I added the javadoc and generated it. All changes are now on origin master.
